import { copyFile, mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";

const rootDir = path.resolve(import.meta.dirname, "..");
const publicRuntimeDir = path.join(rootDir, "public", "local-agent-space");
const petsOutDir = path.join(publicRuntimeDir, "pets");
const manifestPath = path.join(publicRuntimeDir, "pet-manifest.json");
const agentStatePath = path.join(publicRuntimeDir, "agent-state.json");

const rowStates = {
  idle: { row: 0, frames: 6, durations: [280, 110, 110, 140, 140, 320] },
  "running-right": { row: 1, frames: 8, durations: [120, 120, 120, 120, 120, 120, 120, 220] },
  "running-left": { row: 2, frames: 8, durations: [120, 120, 120, 120, 120, 120, 120, 220] },
  waving: { row: 3, frames: 4, durations: [140, 140, 140, 280] },
  jumping: { row: 4, frames: 5, durations: [140, 140, 140, 140, 280] },
  failed: { row: 5, frames: 8, durations: [140, 140, 140, 140, 140, 140, 140, 240] },
  waiting: { row: 6, frames: 6, durations: [150, 150, 150, 150, 150, 260] },
  running: { row: 7, frames: 6, durations: [120, 120, 120, 120, 120, 220] },
  review: { row: 8, frames: 6, durations: [150, 150, 150, 150, 150, 280] },
};

const stateToAnimation = {
  idle: "idle",
  thinking: "review",
  coding: "running",
  tool_calling: "running",
  waiting_user: "waiting",
  error: "failed",
  done: "waving",
};

function codexHome() {
  return process.env.CODEX_HOME || path.join(os.homedir(), ".codex");
}

function slug(value) {
  return String(value || "pet")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "pet";
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}

async function exists(filePath) {
  try {
    await stat(filePath);
    return true;
  } catch {
    return false;
  }
}

async function discoverPets() {
  const sourceHome = codexHome();
  const sourcePetsDir = path.join(sourceHome, "pets");
  if (!(await exists(sourcePetsDir))) return [];

  const entries = await readdir(sourcePetsDir, { withFileTypes: true });
  const candidates = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const petDir = path.join(sourcePetsDir, entry.name);
    const petJsonPath = path.join(petDir, "pet.json");
    if (!(await exists(petJsonPath))) continue;

    let petJson;
    try {
      petJson = await readJson(petJsonPath);
    } catch (error) {
      console.warn(`Skipping invalid pet.json in ${petDir}: ${error.message}`);
      continue;
    }

    const spriteRelative = petJson.spritesheetPath || "spritesheet.webp";
    const sourceSpritePath = path.resolve(petDir, spriteRelative);
    if (!(await exists(sourceSpritePath))) continue;

    candidates.push({
      sourceDir: petDir,
      sourcePetJsonPath: petJsonPath,
      sourceSpritePath,
      id: slug(petJson.id || entry.name),
      displayName: petJson.displayName || petJson.id || entry.name,
      description: petJson.description || "",
      spriteFileName: path.basename(sourceSpritePath),
    });
  }
  return candidates;
}

async function importPet(pet) {
  const outDir = path.join(petsOutDir, pet.id);
  await mkdir(outDir, { recursive: true });
  await copyFile(pet.sourcePetJsonPath, path.join(outDir, "pet.json"));
  await copyFile(pet.sourceSpritePath, path.join(outDir, pet.spriteFileName));
  return {
    id: pet.id,
    displayName: pet.displayName,
    description: pet.description,
    spritesheetPath: `/local-agent-space/pets/${pet.id}/${pet.spriteFileName}`,
    source: "codex-home",
    frameGrid: {
      columns: 8,
      rows: 9,
      cellWidth: 192,
      cellHeight: 208,
      states: rowStates,
    },
    stateToAnimation,
  };
}

async function writeManifest(importedPets) {
  const activePet = importedPets[0] || null;
  const manifest = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    sourceCodexHome: codexHome(),
    activePetId: activePet?.id || null,
    pets: Object.fromEntries(importedPets.map((pet) => [pet.id, pet])),
    notes: [
      "Local runtime files are generated by npm run setup:local and are ignored by git.",
      "Only pet visual assets and abstract agent state are exposed to the browser.",
    ],
  };
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return manifest;
}

async function ensureAgentState(activePetId) {
  if (existsSync(agentStatePath)) return;
  const state = {
    schemaVersion: 1,
    agentId: "codex-local",
    petId: activePetId || null,
    status: "idle",
    taskLabel: "本地待机",
    activeTool: null,
    updatedAt: new Date().toISOString(),
  };
  await writeFile(agentStatePath, `${JSON.stringify(state, null, 2)}\n`, "utf8");
}

async function main() {
  await mkdir(petsOutDir, { recursive: true });
  const discovered = await discoverPets();
  const importedPets = [];

  if (discovered.length) {
    importedPets.push(await importPet(discovered[0]));
  }

  const manifest = await writeManifest(importedPets);
  await ensureAgentState(manifest.activePetId);

  if (manifest.activePetId) {
    console.log(`Agent Space local setup: imported Codex pet "${manifest.activePetId}".`);
  } else {
    console.log("Agent Space local setup: no Codex pet found, using built-in fallback agent.");
  }
  console.log(`Agent state: ${path.relative(rootDir, agentStatePath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
